/**
 * Mock Data Service
 * Centralized mock data for development and testing
 */

export const MOCK_POSTS = [
    {
        id: 'mock-1',
        cafeName: '블루보틀 성수',
        coffeeName: '뉴올리언스',
        location: '서울 성동구',
        imageUrl: 'https://images.unsplash.com/photo-1630040995437-80b01c5dd52d?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxsYXR0ZSUyMGFydCUyMGNvZmZlZSUyMGN1cHxlbnwxfHx8fDE3NjM3MTAzODZ8MA&ixlib=rb-4.1.0&q=80&w=1080',
        rating: 4.8,
        tags: ['달콤함', '부드러움', '시그니처'],
        flavorProfile: {
            acidity: 2,
            sweetness: 5,
            body: 4,
            bitterness: 2,
            aroma: 4,
        },
        userId: 'mock-user-1',
        author: {
            name: '커피러버',
            avatar: 'https://i.pravatar.cc/150?u=1',
            level: 'Barista',
        },
        description: '블루보틀의 시그니처 메뉴. 치커리와 섞은 콜드브루에 우유와 유기농 설탕을 넣어 달콤하고 부드러운 맛이 일품입니다.',
        likes: 124,
        comments: 12,
        date: '2시간 전',
    },
    {
        id: 'mock-2',
        cafeName: '앤트러사이트 합정',
        coffeeName: '공기와 꿈 드립',
        location: '서울 마포구',
        imageUrl: 'https://images.unsplash.com/photo-1550559256-32644b7a2993?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxwb3VyJTIwb3ZlciUyMGNvZmZlZSUyMGJyZXdpbmd8ZW58MXx8fHwxNzYzNjMyMDA4fDA&ixlib=rb-4.1.0&q=80&w=1080',
        rating: 4.5,
        tags: ['산미', '꽃향기', '깔끔함'],
        flavorProfile: {
            acidity: 5,
            sweetness: 3,
            body: 2,
            bitterness: 1,
            aroma: 5,
        },
        userId: 'mock-user-2',
        author: {
            name: '브루잉마스터',
            avatar: 'https://i.pravatar.cc/150?u=2',
            level: 'Pro',
        },
        description: '에티오피아 원두 특유의 화사한 산미가 돋보입니다. 식으면서 더 살아나는 베리류의 향미가 매력적이에요.',
        likes: 89,
        comments: 5,
        date: '5시간 전',
    },
    {
        id: 'mock-3',
        cafeName: '프릳츠 도화',
        coffeeName: '잘 되어 가시나',
        location: '서울 마포구',
        imageUrl: 'https://images.unsplash.com/photo-1674141867738-38c11cc707cf?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxjb2ZmZWUlMjBiZWFucyUyMHRleHR1cmV8ZW58MXx8fHwxNzYzNzEwMzg2fDA&ixlib=rb-4.1.0&q=80&w=1080',
        rating: 4.7,
        tags: ['밸런스', '견과류', '데일리'],
        flavorProfile: {
            acidity: 3,
            sweetness: 4,
            body: 4,
            bitterness: 3,
            aroma: 3,
        },
        userId: 'mock-user-3',
        author: {
            name: '데일리커피',
            avatar: 'https://i.pravatar.cc/150?u=3',
            level: 'Starter',
        },
        description: '매일 마셔도 질리지 않는 훌륭한 밸런스. 고소한 견과류의 풍미와 은은한 단맛이 조화롭습니다.',
        likes: 210,
        comments: 34,
        date: '1일 전',
    },
    {
        id: 'mock-4',
        cafeName: '모모스 커피',
        coffeeName: '에스 쇼콜라',
        location: '부산 영도구',
        imageUrl: 'https://images.unsplash.com/photo-1751956066306-c5684cbcf385?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxtb2Rlcm4lMjBjYWZlJTIwaW50ZXJpb3IlMjBjb3p5fGVufDF8fHx8MTc2MzcxMDM4Nnww&ixlib=rb-4.1.0&q=80&w=1080',
        rating: 4.9,
        tags: ['다크초콜릿', '묵직함', '라떼추천'],
        flavorProfile: {
            acidity: 1,
            sweetness: 4,
            body: 5,
            bitterness: 4,
            aroma: 3,
        },
        userId: 'mock-user-4',
        author: {
            name: '라떼장인',
            avatar: 'https://i.pravatar.cc/150?u=4',
            level: 'Expert',
        },
        description: '이름처럼 다크 초콜릿의 쌉싸름함과 단맛이 진하게 느껴집니다. 우유와 섞였을 때 그 진가가 발휘되는 원두.',
        likes: 156,
        comments: 18,
        date: '2일 전',
    },
];
